import type { NextPage } from 'next'
import Head from 'next/head'
import { useSelector } from 'react-redux'
const Index: NextPage<any> = () => {
  const user: any = useSelector<any>(({ user }) => user)
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex items-center justify-center h-screen'>
        <div className='text-center'>
          <div className='font-semibold text-3xl mb-2 capitalize'>
            {user?.username ? (
              <>
                <span className='font-extralight'>Hello </span>
                {user?.username} !
              </>
            ) : (
              'Admin Page'
            )}
          </div>
          <div className='text-gray-500 font-light'>You are accessing a protected page</div>
        </div>
      </div>
    </>
  )
}
export default Index
