import type { NextPage } from 'next'
import Head from 'next/head'

const Index: NextPage<any> = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex items-center justify-center h-screen'>
        <div className='text-center'>
          <div className='font-semibold text-3xl mb-2'>Home Page</div>
          <div className='text-gray-500 font-light'>Anyone can view this page</div>
        </div>
      </div>
    </>
  )
}

export default Index
